### ISSUE TITLE
✨ Feat: Signer page

### ISSUE THREAD

**Issue by z0r0z** [kalidao/keep-ui#16]
When you click on signers, it should show the whole crew and any other Keep tokens they hold (gallery style pop up like we have in kali dao treasury for nft viewing). We naturally limit preview to maybe 5 to preserve box size: 
![image](https://user-images.githubusercontent.com/92001561/211004820-a74cec65-618a-4e80-a881-f2a55a7baf19.png)

**Comment by nerderlyne** [comment]
Will add [scroll](https://ui.shadcn.com/docs/primitives/scroll-area)
